name: Test install Script

on:
  pull_request:
    branches:
        - main

jobs:
  install:
    name: Run install script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: First run
        run: ./install

      - name: Second run (idempotency check)
        run: ./install