name: Test install Script

on:
  pull_request:
    branches:
        - main

jobs:
  install:
    name: Run install script
    runs-on: ubuntu-latest
    env:
      GIT_NAME: Test User
      GIT_EMAIL: test@example.com

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Syntax check
        run: bash -n install bootstrap

      - name: install --root (first run)
        run: sudo ./install --root

      - name: install --root (idempotency check)
        run: sudo ./install --root

      - name: install --user (first run)
        run: ./install --user

      - name: install --user (idempotency check)
        run: ./install --user
